name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        options: ['dev', 'test', 'qa', 'prod']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to ${{ matrix.env }}
        run: |
          echo "Deploying to ${{ matrix.env }}"
      - name: Execute additional steps
        if: ${{ matrix.env == 'test' || matrix.env == 'qa' || matrix.env == 'prod' }}
        run: |
          echo "Executing additional steps for ${{ matrix.env }}"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: deploy
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests on ${{ matrix.env }}
        run: |
          echo "Running tests on ${{ matrix.env }}"

  perf-test:
    name: Performance Test
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run performance tests on ${{ matrix.env }}
        if: ${{ matrix.env == 'qa' }}
        run: |
          echo "Running performance tests on ${{ matrix.env }}"

  api-test:
    name: API Test
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run API tests on ${{ matrix.env }}
        if: ${{ matrix.env == 'qa' }}
        run: |
          echo "Running API tests on ${{ matrix.env }}"

  post-checks:
    name: Post-Checks
    runs-on: ubuntu-latest
    needs: deploy
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run post-checks on ${{ matrix.env }}
        if: ${{ matrix.env == 'prod' }}
        run: |
          echo "Running post-checks on ${{ matrix.env }}"
