name: Deployment Workflow with matrix demo1

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        options: ['dev', 'test', 'qa', 'prod']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploying..."

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        if: startsWith(matrix.env, 'test') || startsWith(matrix.env, 'qa')
        run: |
          echo "Running tests..."

  perf-test:
    name: Performance Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run performance tests
        if: startsWith(matrix.env, 'qa')
        run: |
          echo "Running performance tests..."

  api-test:
    name: API Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run API tests
        if: startsWith(matrix.env, 'qa')
        run: |
          echo "Running API tests..."

  post-checks:
    name: Post-Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [${{ github.event.inputs.env }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run post-checks
        if: startsWith(matrix.env, 'prod')
        run: |
          echo "Running post-checks..."
