name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        options: ${{ secrets.REPOSITORY_ENVIRONMENTS }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.env == 'dev' || github.event.inputs.env == 'test' || github.event.inputs.env == 'qa' || github.event.inputs.env == 'prod' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploying..."

  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.env == 'test' || github.event.inputs.env == 'qa' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Running tests..."

  perf-test:
    name: Performance Test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.env == 'qa' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run performance tests
        run: |
          echo "Running performance tests..."

  api-test:
    name: API Test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.env == 'qa' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run API tests
        run: |
          echo "Running API tests..."

  post-checks:
    name: Post-Checks
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.env == 'prod' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run post-checks
        run: |
          echo "Running post-checks..."
